# docker network create mynetwork
# docker run -d --name web1 --net mynetwork jmalloc/echo-server
# docker run -d --name web2 --net mynetwork jmalloc/echo-server
# docker run -d --name web3 --net mynetwork jmalloc/echo-server
# docker run -d --name haproxy --net mynetwork \
# -v $(pwd):/usr/local/etc/haproxy:ro -p 80:80 haproxytech/haproxy-alpine:2.7

services:
  web1:
    # 이름 쪽으로 넘기게 설정해둬서 컨테이너 이름 지정해둠
    # haproxy.cfg
    # backend app
    # balance     roundrobin
    # server  s1 web1:8080 check
    # server  s2 web2:8080 check
    # server  s3 web3:8080 check
    container_name: web1
    image: jmalloc/echo-server

  web2:
    container_name: web2
    image: jmalloc/echo-server

  web3:
    container_name: web3
    image: jmalloc/echo-server

  haproxy:
    container_name: haproxy
    image: haproxytech/haproxy-alpine:2.7
    ports:
      - "80:80"
    volumes:
      - "./config:/usr/local/etc/haproxy:ro"